-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzCHP8LlBNGRBp5DW
gDWykZ/kJJcmBO9SY2f+8KOc4E6gCgYIKoZIzj0DAQehRANCAATmEZ1EZksLOhGw
fDL28wMyZgvbEERQP5hFouW0eOMOXNHxYyMgPl1f9FMwjUyTtmaZ6+2dh9LuFCs1
swOOv9CS
-----END PRIVATE KEY-----