version: '3'

vars:
  ENVIRONMENT: '{{.ENV_ENVIRONMENT | default "dev"}}'
  BUILD_CONFIG: '{{.BUILD_CONFIG | default "Release"}}'
  TERRAFORM_VARS: 'terraform/environments/{{.ENVIRONMENT}}.tfvars'

tasks:
  default:
    desc: Show available commands
    cmds:
    - task: help

  help:
    desc: Display help information
    cmds:
    - |
      echo "Backend Build and Deployment Tasks"
      echo "===================================="
      echo ""
      echo "Environment: {{.ENVIRONMENT}}"
      echo "Config: {{.BUILD_CONFIG}}"
      echo ""
      echo "Usage: task [-e ENVIRONMENT] <task>"
      echo ""
      echo "Available tasks:"
      task --list

  build:
    desc: Build .NET solution
    dir: backend
    cmds:
    - dotnet build src/MindBodyDictionary.Backend.sln -c {{.BUILD_CONFIG}}
    sources:
    - src/**/*.cs
    - src/**/*.csproj
    generates:
    - bin/**/*

  rebuild:
    desc: Clean and rebuild .NET solution
    dir: backend
    cmds:
    - dotnet clean src/MindBodyDictionary.Backend.sln
    - dotnet build src/MindBodyDictionary.Backend.sln -c {{.BUILD_CONFIG}}

  publish:
    desc: Publish Azure Functions
    dir: backend
    deps:
    - build
    cmds:
    - dotnet publish src/MindBodyDictionary.AdminApi -c {{.BUILD_CONFIG}} -o ./publish
    generates:
    - publish/**/*

  test:
    desc: Run tests
    dir: backend
    cmds:
    - dotnet test src/MindBodyDictionary.Backend.sln -c {{.BUILD_CONFIG}}

  lint:
    desc: Run code analysis
    dir: backend
    cmds:
    - dotnet format src/MindBodyDictionary.Backend.sln --verify-no-changes --verbosity diagnostic || true

  tf:init:
    desc: Initialize Tofu (OpenTofu)
    dir: backend/terraform
    cmds:
      - tofu init -backend=false

  tf:validate:
    desc: Validate Tofu configuration
    dir: backend/terraform
    cmds:
    - tofu validate

  tf:fmt:
    desc: Format Tofu files
    dir: backend/terraform
    cmds:
    - tofu fmt -recursive

  tf:plan:
    desc: Plan Tofu deployment
    cmds:
      - cd backend/terraform && tofu plan -var-file=environments/{{.ENVIRONMENT}}.tfvars -out=tfplan

  tf:apply:
    desc: Apply Tofu deployment
    dir: backend/terraform
    deps:
      - tf:init
    cmds:
      - |
        if [ -f "tfplan" ]; then
          tofu apply tfplan
          rm tfplan
        else
          tofu apply -var-file=environments/{{.ENVIRONMENT}}.tfvars
        fi

  tf:destroy:
    desc: Destroy Tofu-managed resources
    dir: backend/terraform
    cmds:
      - tofu destroy -var-file=environments/{{.ENVIRONMENT}}.tfvars

  tf:output:
    desc: Display Tofu outputs
    dir: backend/terraform
    cmds:
    - tofu output

  deploy:infra:
    desc: Deploy infrastructure (Terraform)
    deps:
    - tf:init
    - tf:validate
    - tf:plan
    - tf:apply

  deploy:functions:
    desc: Build and publish functions
    deps:
    - build
    - publish

  deploy:
    desc: Full deployment - infrastructure and functions
    deps:
    - deploy:infra
    - deploy:functions
    cmds:
    - echo "✓ Infrastructure and functions deployed successfully"

  env:list:
    desc: List available environments
    cmds:
    - |
      echo "Available environments:"
      ls -1 backend/terraform/environments/*.tfvars | xargs -n1 basename | sed 's/.tfvars//'

  clean:
    desc: Clean build artifacts
    dir: backend
    cmds:
    - dotnet clean src/MindBodyDictionary.Backend.sln
    - rm -rf bin obj publish

  info:
    desc: Display deployment info
    cmds:
    - |
      echo "=== MindBodyDictionary Backend ==="
      echo "Environment: {{.ENVIRONMENT}}"
      echo "Build Config: {{.BUILD_CONFIG}}"
      echo "Terraform Vars: {{.TERRAFORM_VARS}}"
      echo ""
      echo "Solution: backend/src/MindBodyDictionary.Backend.sln"
      echo "Admin API: backend/src/MindBodyDictionary.AdminApi"

  vscode:deploy:
    desc: Deploy to Azure from VS Code (requires Azure Functions extension)
    cmds:
    - echo "Opening VS Code deployment dialog..."
    - echo "1. Press Cmd+Shift+P (Mac) or Ctrl+Shift+P (Windows)"
    - echo "2. Search for Azure Functions Deploy to Function App"
    - echo "3. Select subscription and function app"

  vscode:logs:
    desc: Stream logs from Azure Function App
    cmds:
    - az functionapp log tail --name mbd-admin-api --resource-group mbd-backend-rg

  vscode:config:
    desc: Show current app settings
    cmds:
    - az functionapp config appsettings list --name mbd-admin-api --resource-group mbd-backend-rg --output table

  vscode:run:
    desc: Run functions locally (F5 in VS Code)
    dir: backend/src/MindBodyDictionary.AdminApi
    cmds:
    - func start

  vscode:test:
    desc: Test functions locally with curl
    cmds:
    - |
      echo "Testing local functions at http://localhost:7071"
      echo ""
      echo "Available functions:"
      curl -s http://localhost:7071/api/functions 2>/dev/null || echo "Functions not running. Start with 'task vscode:run'"
